### ISSUE TITLE
设置规则不起作用

### ISSUE THREAD

**Issue by pz9042** [coconilu/easy-inspector#1]
![image](https://user-images.githubusercontent.com/5012019/86076279-59b6ed80-babc-11ea-82be-0b2785bcf7dc.png)

访问 http://192.168.1.187:84/set/Devicegroup/list，服务端并没有收到这个添加的header

**Comment by pz9042** [comment]
搞明白了，这个规则默认是关闭的。要在手动点击全部开启

**Comment by coconilu** [comment]
嗯，是的，有总开关和每个rule的开关，主要是为了方便用户细分自己的规则。谢谢你的提问。
